### ISSUE TITLE
Error on loading external style with custom font

### ISSUE THREAD

**Issue by ptitdam2001** [caroso1222/ng-lib-schematics#12]
I would like to use another npm library with it CSS and font but after building my library, I can't load the font because the path of font-face is relative.

How could I resolve my problem?

**Comment by NetanelBasal** [comment]
That's not related to the library, google for an answer.

**Comment by caroso1222** [comment]
Thanks @ptitdam2001 for opening the ticket. You might want to research about how to expose a node package which consumes a static resource from another node package, and how well that plays with webpack and perhaps css-loader. Maybe avoiding relative paths to like `.../.../node_modules/pkg/font.woff` and using `~/pkg/font.woff` does the trick? I'm not sure.

As suggested by @NetanelBasal, this is not related to this particular library, so I'll close this issue. Please share with us your solution if you happen to find one!

Thanks @NetanelBasal for looking into this.

**Comment by ptitdam2001** [comment]
@caroso1222 I develop my own Angular module with ng-lib-schematics, but there is a dependency with a node package using its stylesheet. My question is totally in relationshig with the library because on building with gulp, css style of component are manipulated.  

I would like to know if I should use ng-lib-schematics to build an angular module with some external dependancies.

Sorry if it is not an issue, I think it is an important condition for using the library or not

**Comment by NetanelBasal** [comment]
If you require the scss file inside your component it should include it within the component.

**Comment by caroso1222** [comment]
@ptitdam2001 yes, all the static assets should be shipped from within your library. You can have your dep listed in peerDependencies as well, but if the library is depending on relative assets, then gulp will still complain about it at build time.
