### ISSUE TITLE
Silently fails when running

### ISSUE THREAD

**Issue by bniedermeyer** [caroso1222/ng-lib-schematics#9]
## Summary
When running ng-lib-schematics the process exits without making any changes to the project. No error is thrown. I've also tried running with version 0.2.0 and had the same result.

## Steps to reproduce

```
npm i -g @angular-devkit/core @angular-devkit/schematics-cli ng-lib-schematics
ng new schematics-test --skip-install
schematics ng-lib-schematics:lib-standalone --name lib-test
```

## Output from `ng -v`
I've tried running ng-lib-schematics on a Windows 10 machine both in a normal command line and within WSL (my normal dev environment). Note that below I did run `npm i` so I could display the versions for the core cli libraries but did not install any libraries before running the `schematics` command.
```
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/

Angular CLI: 1.7.3
Node: 8.9.4
OS: win32 x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

```
    _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.7.3
Node: 8.8.0
OS: linux x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

**Comment by NetanelBasal** [comment]
And other `schematics` worked for you?

**Comment by bniedermeyer** [comment]
I don't have a ton of experience with other schematics tools. The only other one I've used is the NgRx schematics and the syntax is a bit different as it's used as a collection for the Angular cli. 

However when I tried running `schematics blank --name=my-component` the same thing happened. 

This may be related to [this issue](https://github.com/angular/devkit/issues/464) in the ng devkit?

**Comment by NetanelBasal** [comment]
Seems like. I don't think it's a bug in the library.

**Comment by bniedermeyer** [comment]
I'll go ahead and close for now and keep an eye on the devkit issue.

**Comment by caroso1222** [comment]
@bniedermeyer thanks for the report and thanks @NetanelBasal for your help troubleshooting it!
